### ISSUE TITLE
GAN conversion distorted

### ISSUE THREAD

**Issue by BostonCodingLeo** [Zeqiang-Lai/DragGAN#25]
Image of Liuyifei after GAN inversion.
![Screenshot 2023-05-23 143232](https://github.com/Zeqiang-Lai/DragGAN/assets/134365109/b3a2b85e-de53-405d-840c-e4601fecc2e1)

**Comment by BostonCodingLeo** [comment]
Original image:

![hTMEa1eaSLBr9VJcoiXuU89MK81](https://github.com/Zeqiang-Lai/DragGAN/assets/134365109/6b21a861-89ac-4097-b157-eafde20e6e83)

**Comment by Zeqiang-Lai** [comment]
Due to the limitation of GAN inversion, it is possible that your custom images are distorted. Besides, it is also possible the manipulations fail due to the limitation of our implementation.

**Comment by Mario100Y** [comment]
> Due to the limitation of GAN inversion, it is possible that your custom images are distorted. Besides, it is also possible the manipulations fail due to the limitation of our implementation.

First of all, thank you for sharing your project. I'm impressed! Now, I have a question:

What are some potential techniques or approaches that can be employed to mitigate the issue of distorted custom images caused by the limitations of GAN inversion?
Additionally, I'm curious about:

Are there any specific strategies or methods that can be used to overcome the implementation limitations that may lead to failures in manipulations?
Please let me know if there's any additional information or context you'd like to provide.

**Comment by BostonCodingLeo** [comment]
> Due to the limitation of GAN inversion, it is possible that your custom images are distorted. Besides, it is also possible the manipulations fail due to the limitation of our implementation.

This is right after the GAN Inversion. No manipulation was used yet.
